blank_issues_enabled: false
contact_links:
  - name: Diskusi & Pertanyaan
    url: https://github.com/Varaaa-arch/InfraForge/discussions
    about: Buat nanya-nanya atau diskusi umum seputar InfraForge