"""add_deployments_table

Revision ID: 166ebf1a4268
Revises: a57f609b5c4b
Create Date: 2026-08-03 17:55:03.793962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166ebf1a4268'
down_revision: Union[str, Sequence[str], None] = 'a57f609b5c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False, comment='Aplikasi yang di-deploy'),
    sa.Column('server_id', sa.Integer(), nullable=True, comment='Target server (nullable — diset NULL jika server dihapus)'),
    sa.Column('status', sa.Enum('pending', 'deploying', 'success', 'failed', name='deployment_status'), server_default='pending', nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False, comment='Branch yang di-deploy'),
    sa.Column('commit_sha', sa.String(length=40), nullable=True, comment='Commit SHA hasil clone (diisi setelah clone selesai)'),
    sa.Column('log_path', sa.Text(), nullable=True, comment='Path file log sementara di server / lokal'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Waktu deployment dimulai'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu deployment selesai (None jika masih berjalan)'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_application_id'), 'deployments', ['application_id'], unique=False)
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_server_id'), 'deployments', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_server_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_application_id'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
