"""add_servers_env_vars_applications_tables

Revision ID: a57f609b5c4b
Revises: 91b157b5aceb
Create Date: 2026-08-02 09:01:41.788327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57f609b5c4b'
down_revision: Union[str, Sequence[str], None] = '91b157b5aceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=253), nullable=False),
    sa.Column('port', sa.Integer(), server_default='22', nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('auth_type', sa.Enum('password', 'private_key', name='server_auth_type'), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'error', name='server_status'), server_default='inactive', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_id'), 'servers', ['id'], unique=False)
    op.create_index(op.f('ix_servers_owner_id'), 'servers', ['owner_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nama aplikasi, misal: backend-api, frontend-web'),
    sa.Column('repository', sa.String(length=500), nullable=True, comment='URL repository Git aplikasi ini'),
    sa.Column('branch', sa.String(length=100), server_default='main', nullable=False, comment='Branch yang akan di-deploy'),
    sa.Column('dockerfile_path', sa.String(length=255), server_default='Dockerfile', nullable=False, comment='Path ke Dockerfile relatif dari root repository'),
    sa.Column('compose_path', sa.String(length=255), server_default='docker-compose.yml', nullable=False, comment='Path ke docker-compose file relatif dari root repository'),
    sa.Column('build_context', sa.String(length=255), nullable=True, comment='Docker build context path (opsional, default: direktori Dockerfile)'),
    sa.Column('status', sa.Enum('idle', 'deploying', 'running', 'failed', name='app_status'), server_default='idle', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_project_id'), 'applications', ['project_id'], unique=False)
    op.create_table('project_env_vars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False, comment='Nama environment variable, misal DATABASE_URL'),
    sa.Column('encrypted_value', sa.Text(), nullable=False, comment='Nilai terenkripsi dengan Fernet; dekripsi via encryption_service'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_project_env_key')
    )
    op.create_index(op.f('ix_project_env_vars_id'), 'project_env_vars', ['id'], unique=False)
    op.create_index(op.f('ix_project_env_vars_project_id'), 'project_env_vars', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_env_vars_project_id'), table_name='project_env_vars')
    op.drop_index(op.f('ix_project_env_vars_id'), table_name='project_env_vars')
    op.drop_table('project_env_vars')
    op.drop_index(op.f('ix_applications_project_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_servers_owner_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_id'), table_name='servers')
    op.drop_table('servers')
    # ### end Alembic commands ###
